"use server";

import { createClient } from "@/lib/supabase/server";
import { getResend } from "@/lib/resend";
import { escapeHtml } from "@/lib/validation";

export async function submitReportToAuthority(reportId: string, authorityId?: string) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) throw new Error("Not authenticated");

  // Fetch report
  const { data: report, error: reportError } = await supabase
    .from("reports")
    .select("*, circles(name, location, lga_code, lga_name, state_code)")
    .eq("id", reportId)
    .single();

  if (reportError || !report) throw new Error("Report not found");

  // Authorization: shepherd of the circle or admin
  const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).single();
  const isAdmin = profile?.role === "admin";

  if (!isAdmin) {
    if (!report.circle_id) throw new Error("Not authorized");
    const { data: shepherd } = await supabase
      .from("circle_shepherds")
      .select("id")
      .eq("circle_id", report.circle_id)
      .eq("user_id", user.id)
      .maybeSingle();
    if (!shepherd) throw new Error("Not authorized to submit this report");
  }

  // Find authority
  let authority;
  if (authorityId) {
    const { data } = await supabase.from("authorities").select("*").eq("id", authorityId).single();
    authority = data;
  } else {
    // Match by circle region
    const circle = report.circles as any;
    const regionType = circle?.lga_code ? "lga" : circle?.state_code ? "state" : null;
    const regionCode = circle?.lga_code ?? circle?.state_code;

    if (regionType && regionCode) {
      const { data } = await supabase
        .from("authorities")
        .select("*")
        .eq("region_type", regionType)
        .eq("region_code", regionCode)
        .eq("authority_type", "council")
        .single();
      authority = data;
    }
  }

  if (!authority || !authority.contact_email) {
    throw new Error("No matching authority with email found. Please add an authority first.");
  }

  const circleName = escapeHtml((report.circles as any)?.name ?? "A Meek Meet Circle");
  const circleLocation = escapeHtml((report.circles as any)?.location ?? "your community");
  const content = (report.content as any) ?? {};
  const summary = escapeHtml(report.summary ?? content.rawSummary ?? "");

  const themesHtml = (content.topThemes ?? [])
    .map(
      (t: any) =>
        `<li><strong>${escapeHtml(t.theme)}</strong> (${t.sentiment}, ${t.count} mentions)</li>`
    )
    .join("");

  const consensusHtml = (content.consensusItems ?? [])
    .map(
      (c: any) =>
        `<li>${escapeHtml(c.statement)} — ${c.agreementLevel}% estimated agreement</li>`
    )
    .join("");

  const html = `
    <div style="font-family: Georgia, serif; max-width: 560px; margin: 0 auto; padding: 32px; background: #faf6ee; color: #2c2c2c;">
      <h1 style="font-size: 22px; margin-bottom: 16px;">Community Voice Report</h1>
      <p style="font-size: 16px; line-height: 1.6;">
        ${circleName}, based in ${circleLocation}, has been gathering regularly through Meek Meet to listen to its members and share concerns with decision-makers.
      </p>
      <p style="font-size: 16px; line-height: 1.6;">
        <strong>Summary:</strong> ${summary}
      </p>
      <div style="background: #f5efe0; border-radius: 12px; padding: 20px; margin: 20px 0;">
        <p style="margin: 0 0 8px;"><strong>Responses collected:</strong> ${content.responseCount ?? 0}</p>
        <p style="margin: 0 0 8px;"><strong>Meetings held:</strong> ${content.meetingCount ?? 0}</p>
        <p style="margin: 0;"><strong>Dominant sentiment:</strong> ${content.sentimentSummary?.dominant ?? "neutral"}</p>
      </div>
      <h2 style="font-size: 18px; margin-top: 24px;">Top Themes</h2>
      <ul style="line-height: 1.6;">${themesHtml}</ul>
      ${consensusHtml ? `<h2 style="font-size: 18px; margin-top: 24px;">Areas of Strong Agreement</h2><ul style="line-height: 1.6;">${consensusHtml}</ul>` : ""}
      <p style="font-size: 14px; color: #6b6b6b; margin-top: 24px;">
        All data is anonymised and aggregated. This report was generated by Meek Meet on behalf of the community.
      </p>
      <hr style="border: 0; border-top: 1px solid #e8e0cc; margin: 24px 0;" />
      <p style="font-size: 12px; color: #6b6b6b;">
        Meek Meet · A warm community of faith
      </p>
    </div>
  `;

  const subject = `Community Voice Report — ${circleName}`;

  try {
    await getResend().emails.send({
      from: "Meek Meet <hello@meekmeet.com>",
      to: authority.contact_email,
      subject,
      html,
    });
  } catch (err) {
    console.error("Failed to send report:", err);
    throw new Error("Failed to send report email");
  }

  // Record submission
  const { error: submissionError } = await supabase.from("authority_submissions").insert({
    authority_id: authority.id,
    report_id: reportId,
    circle_id: report.circle_id,
    submitted_by: user.id,
    submitted_at: new Date().toISOString(),
    status: "delivered",
    subject,
    body_html: html,
  });

  if (submissionError) throw new Error(submissionError.message);

  // Update report status
  await supabase.from("reports").update({ status: "submitted", sent_to_authority_at: new Date().toISOString(), sent_to_authority_email: authority.contact_email }).eq("id", reportId);

  return { success: true, authority: authority.name };
}
