import type { CuratedDailyVerse } from '../types'

/**
 * 28 curated daily verses — enough for a full rotation before repeating.
 * Each verse includes a short interfaith reflection.
 * Uses day-of-year modulo to cycle through them.
 */

const verses: CuratedDailyVerse[] = [
  {
    tradition: 'bible',
    bookId: 'genesis',
    book: 'Genesis',
    chapter: 1,
    verse: 1,
    text: 'In the beginning God created the heaven and the earth.',
    reflection: 'Every tradition begins with wonder. Today, let yourself be amazed by existence itself.',
    theme: 'Creation',
  },
  {
    tradition: 'quran',
    bookId: '1',
    book: 'Al-Fatihah',
    chapter: 1,
    verse: 1,
    text: 'In the name of Allah, the Beneficent, the Merciful.',
    reflection: 'The opening of every prayer begins with mercy. How might you open your day the same way?',
    theme: 'Mercy',
  },
  {
    tradition: 'tanakh',
    bookId: 'psalms',
    book: 'Psalms',
    chapter: 23,
    verse: 1,
    text: 'The Lord is my shepherd; I shall not want.',
    reflection: 'To be shepherded is to be known, guided, and provided for. Rest in that trust today.',
    theme: 'Trust',
  },
  {
    tradition: 'buddhist',
    bookId: 'dhammapada',
    book: 'The Dhammapada',
    chapter: 1,
    verse: 1,
    text: 'All that we are is the result of what we have thought: it is founded on our thoughts, it is made up of our thoughts.',
    reflection: 'Your mind is the architect of your world. What are you building today?',
    theme: 'Mindfulness',
  },
  {
    tradition: 'mormon',
    bookId: '1_nephi',
    book: '1 Nephi',
    chapter: 1,
    verse: 1,
    text: 'I, Nephi, having been born of goodly parents, therefore I was taught somewhat in all the learning of my father...',
    reflection: 'Gratitude for those who taught us is the first rung on the ladder of wisdom.',
    theme: 'Gratitude',
  },
  {
    tradition: 'bible',
    bookId: 'matthew',
    book: 'Matthew',
    chapter: 5,
    verse: 44,
    text: 'But I say unto you, Love your enemies, bless them that curse you...',
    reflection: 'The most radical teaching in religious history: not tolerance, but love. Who needs your blessing today?',
    theme: 'Love',
  },
  {
    tradition: 'quran',
    bookId: '2',
    book: 'Al-Baqarah',
    chapter: 2,
    verse: 286,
    text: 'Allah tasketh not a soul beyond its scope. For it (is only) that which it hath earned, and against it (only) that which it hath deserved.',
    reflection: 'You are not asked to carry more than you can bear. Be gentle with yourself.',
    theme: 'Grace',
  },
  {
    tradition: 'tanakh',
    bookId: 'micah',
    book: 'Micah',
    chapter: 6,
    verse: 8,
    text: 'He hath shewed thee, O man, what is good; and what doth the Lord require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?',
    reflection: 'Three things: justice, mercy, humility. No ritual, no pilgrimage — just this tripod of integrity.',
    theme: 'Justice',
  },
  {
    tradition: 'buddhist',
    bookId: 'dhammapada',
    book: 'The Dhammapada',
    chapter: 1,
    verse: 5,
    text: 'For hatred does not cease by hatred at any time: hatred ceases by love, this is an old rule.',
    reflection: 'A law of nature, not a preference. Only love interrupts the chain of harm.',
    theme: 'Forgiveness',
  },
  {
    tradition: 'mormon',
    bookId: 'mosiah',
    book: 'Mosiah',
    chapter: 2,
    verse: 17,
    text: 'When ye are in the service of your fellow beings ye are only in the service of your God.',
    reflection: 'Service is not a detour from spirituality — it is its very definition.',
    theme: 'Service',
  },
  {
    tradition: 'bible',
    bookId: 'luke',
    book: 'Luke',
    chapter: 10,
    verse: 33,
    text: 'But a certain Samaritan, as he journeyed, came where he was: and when he saw him, he had compassion on him.',
    reflection: 'The outsider became the hero. Compassion does not ask about merit — it kneels beside blood.',
    theme: 'Compassion',
  },
  {
    tradition: 'quran',
    bookId: '55',
    book: 'Ar-Rahman',
    chapter: 55,
    verse: 13,
    text: 'Which is it, of the favours of your Lord, that ye deny?',
    reflection: 'This refrain repeats 31 times. Look around you: what favour have you taken for granted today?',
    theme: 'Gratitude',
  },
  {
    tradition: 'tanakh',
    bookId: 'psalms',
    book: 'Psalms',
    chapter: 46,
    verse: 10,
    text: 'Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.',
    reflection: 'Stillness is not emptiness — it is the posture of recognition. Stop, and know.',
    theme: 'Stillness',
  },
  {
    tradition: 'buddhist',
    bookId: 'dhammapada',
    book: 'The Dhammapada',
    chapter: 12,
    verse: 165,
    text: 'By oneself the evil is done, by oneself one suffers; by oneself the evil is left undone, by oneself one is purified.',
    reflection: 'You are your own refuge. No one can purify another.',
    theme: 'Agency',
  },
  {
    tradition: 'mormon',
    bookId: 'moroni',
    book: 'Moroni',
    chapter: 10,
    verse: 4,
    text: 'And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true...',
    reflection: 'Truth is not imposed — it is invited. Ask, with real intent, and see what answers.',
    theme: 'Truth',
  },
  {
    tradition: 'bible',
    bookId: 'john',
    book: 'John',
    chapter: 1,
    verse: 5,
    text: 'And the light shineth in darkness; and the darkness comprehended it not.',
    reflection: 'Light does not need darkness to exist — but darkness cannot overcome it. Be light today.',
    theme: 'Light',
  },
  {
    tradition: 'quran',
    bookId: '2',
    book: 'Al-Baqarah',
    chapter: 2,
    verse: 195,
    text: 'Spend of your good things and render not evil for evil. Do good. Lo! Allah loveth the beneficent.',
    reflection: 'Ihsan: doing beautiful things beautifully. Let your smallest act today be a work of art.',
    theme: 'Beauty',
  },
  {
    tradition: 'tanakh',
    bookId: 'proverbs',
    book: 'Proverbs',
    chapter: 3,
    verse: 5,
    text: 'Trust in the Lord with all thine heart; and lean not unto thine own understanding.',
    reflection: 'Understanding has limits. Trust is the bridge across what you cannot yet see.',
    theme: 'Trust',
  },
  {
    tradition: 'buddhist',
    bookId: 'dhammapada',
    book: 'The Dhammapada',
    chapter: 5,
    verse: 50,
    text: 'Let a man overcome anger by love, let him overcome evil by good...',
    reflection: 'Every negative force has a positive counterforce. What will you dissolve with love today?',
    theme: 'Love',
  },
  {
    tradition: 'mormon',
    bookId: 'alma',
    book: 'Alma',
    chapter: 37,
    verse: 6,
    text: 'By small and simple things are great things brought to pass...',
    reflection: 'You do not need a grand gesture. A small kindness, a simple prayer — these move mountains.',
    theme: 'Simplicity',
  },
  {
    tradition: 'bible',
    bookId: 'romans',
    book: 'Romans',
    chapter: 12,
    verse: 2,
    text: 'And be not conformed to this world: but be ye transformed by the renewing of your mind...',
    reflection: 'Transformation is an inside job. The world shapes you by default; you must choose to be remade.',
    theme: 'Transformation',
  },
  {
    tradition: 'quran',
    bookId: '94',
    book: 'Ash-Sharh',
    chapter: 94,
    verse: 5,
    text: 'But lo! with hardship goeth ease, lo! with hardship goeth ease.',
    reflection: 'The verse repeats ease twice — as if to say: however many times difficulty comes, relief comes double.',
    theme: 'Hope',
  },
  {
    tradition: 'tanakh',
    bookId: 'isaiah',
    book: 'Isaiah',
    chapter: 41,
    verse: 10,
    text: 'Fear thou not; for I am with thee: be not dismayed; for I am thy God...',
    reflection: 'Four commands, four promises. Fear not — I am with you. Do not be dismayed — I strengthen you.',
    theme: 'Courage',
  },
  {
    tradition: 'buddhist',
    bookId: 'dhammapada',
    book: 'The Dhammapada',
    chapter: 25,
    verse: 361,
    text: 'He who holds back rising anger like a rolling chariot, him I call a real driver; other people are but holding the reins.',
    reflection: 'Anger is energy. Most people are dragged by it. The wise one steers.',
    theme: 'Self-Control',
  },
  {
    tradition: 'mormon',
    bookId: '2_nephi',
    book: '2 Nephi',
    chapter: 25,
    verse: 26,
    text: 'And we talk of Christ, we rejoice in Christ, we preach of Christ, we prophesy of Christ...',
    reflection: 'What you speak of most is what you worship. What fills your conversation today?',
    theme: 'Joy',
  },
  {
    tradition: 'bible',
    bookId: 'galatians',
    book: 'Galatians',
    chapter: 5,
    verse: 22,
    text: 'But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith...',
    reflection: 'Fruit grows. It is not manufactured. What soil are you planting yourself in today?',
    theme: 'Growth',
  },
  {
    tradition: 'quran',
    bookId: '2',
    book: 'Al-Baqarah',
    chapter: 2,
    verse: 153,
    text: 'O ye who believe! Seek help in patience and prayer; lo! Allah is with the steadfast.',
    reflection: 'Patience (sabr) is not passive waiting — it is active endurance, rooted in trust.',
    theme: 'Patience',
  },
  {
    tradition: 'tanakh',
    bookId: 'ecclesiastes',
    book: 'Ecclesiastes',
    chapter: 3,
    verse: 1,
    text: 'To every thing there is a season, and a time to every purpose under the heaven.',
    reflection: 'Whatever season you are in — planting or reaping, weeping or laughing — it belongs. Trust the rhythm.',
    theme: 'Seasons',
  },
]

export function getCuratedDailyVerse(): CuratedDailyVerse {
  const now = new Date()
  const start = new Date(now.getFullYear(), 0, 0)
  const diff = now.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  return verses[dayOfYear % verses.length]
}

export function getCuratedVerseForDate(date: Date): CuratedDailyVerse {
  const start = new Date(date.getFullYear(), 0, 0)
  const diff = date.getTime() - start.getTime()
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24))
  return verses[dayOfYear % verses.length]
}
