export interface RevolutionaryQuestion {
  id: string
  category: string
  question: string
  context: string
}

export const questionCategories = [
  "Community",
  "Governance",
  "Environment",
  "Family",
  "Economy",
  "Education",
  "Health",
  "Justice",
  "Technology",
  "Culture",
] as const

export const revolutionaryQuestions: RevolutionaryQuestion[] = [
  {
    id: "comm-1",
    category: "Community",
    question: "What is the single greatest unmet need in your local community, and who is already trying to meet it?",
    context: "Identifies gaps and existing efforts to avoid duplication and find collaboration.",
  },
  {
    id: "comm-2",
    category: "Community",
    question: "How do the elderly, the isolated, and the newcomer experience your neighbourhood? What would they change?",
    context: "Surfaces perspectives often excluded from community planning.",
  },
  {
    id: "comm-3",
    category: "Community",
    question: "What local institution -- school, place of gathering, business, or club -- has the most untapped potential to serve the community?",
    context: "Reveals underutilised assets already present in the area.",
  },
  {
    id: "comm-4",
    category: "Community",
    question: "Where do neighbours most often help each other, and where does the help fall short?",
    context: "Maps informal mutual aid networks and their breaking points.",
  },
  {
    id: "comm-5",
    category: "Community",
    question: "What public space in your area feels most welcoming, and which feels most exclusionary? Why?",
    context: "Reveals how physical space shapes social belonging.",
  },
  {
    id: "comm-6",
    category: "Community",
    question: "When someone in your community falls into crisis, what is the first place they turn -- and is it enough?",
    context: "Surfaces the real safety net versus the official one.",
  },
  {
    id: "comm-7",
    category: "Community",
    question: "What event or gathering brought your community closest together in recent memory, and what made it work?",
    context: "Identifies the conditions that generate genuine social cohesion.",
  },
  {
    id: "comm-8",
    category: "Community",
    question: "Who in your community works hardest for others but receives the least recognition?",
    context: "Surfaces invisible labour and undervalued contributors.",
  },
  {
    id: "comm-9",
    category: "Community",
    question: "What boundary -- physical, social, or economic -- most divides your community, and what would it take to bridge it?",
    context: "Confronts segregation and separation in everyday life.",
  },
  {
    id: "comm-10",
    category: "Community",
    question: "If every adult in your neighbourhood contributed two hours a week to a shared project, what should that project be?",
    context: "Imagines collective action at a hyper-local scale.",
  },
  {
    id: "comm-11",
    category: "Community",
    question: "What service or resource do people travel outside your community to find, when it could exist locally?",
    context: "Identifies economic and social leakage from the local area.",
  },
  {
    id: "comm-12",
    category: "Community",
    question: "How has your community changed in the last ten years -- and who mourned those changes, and who celebrated them?",
    context: "Surfaces conflicting narratives about progress and loss.",
  },
  {
    id: "comm-13",
    category: "Community",
    question: "What small act of neighbourliness has had an outsized impact on someone you know?",
    context: "Elevates everyday kindness as a community-building force.",
  },
  {
    id: "comm-14",
    category: "Community",
    question: "What group in your community is growing fastest, and what infrastructure does not yet exist to welcome them?",
    context: "Anticipates demographic shifts and preparation gaps.",
  },
  {
    id: "comm-15",
    category: "Community",
    question: "If you had to describe your community to a stranger in one true sentence, what would you say -- and what would you leave out?",
    context: "Reveals the stories a community tells about itself and its silences.",
  },
  {
    id: "gov-1",
    category: "Governance",
    question: "What law or policy most frustrates the people in your region, and what would a fair alternative look like?",
    context: "Captures ground-level policy pain points for evidence-based advocacy.",
  },
  {
    id: "gov-2",
    category: "Governance",
    question: "If you could redesign how local decisions are made, what would you change about who gets a voice and when?",
    context: "Explores democratic participation and representation gaps.",
  },
  {
    id: "gov-3",
    category: "Governance",
    question: "What issue do local representatives avoid discussing that everyone in your area actually cares about?",
    context: "Identifies the gap between political discourse and public concern.",
  },
  {
    id: "gov-4",
    category: "Governance",
    question: "When was the last time a government decision in your region genuinely improved daily life -- and how did people know it happened?",
    context: "Measures perceived government effectiveness and communication.",
  },
  {
    id: "gov-5",
    category: "Governance",
    question: "Who benefits most from the current way decisions are made in your area, and who is systematically excluded?",
    context: "Surfaces power asymmetries in local governance.",
  },
  {
    id: "gov-6",
    category: "Governance",
    question: "What public service works so well that people take it for granted -- and what would happen if it disappeared?",
    context: "Values functional systems before they are threatened.",
  },
  {
    id: "gov-7",
    category: "Governance",
    question: "How much do you trust that your taxes are being spent wisely in your region -- and what would restore or deepen that trust?",
    context: "Explores the foundation of fiscal consent.",
  },
  {
    id: "gov-8",
    category: "Governance",
    question: "What is the most significant promise made by a local leader that was broken -- and why did it matter?",
    context: "Tracks accountability and the cost of broken trust.",
  },
  {
    id: "gov-9",
    category: "Governance",
    question: "If a sixteen-year-old could vote on one local issue, which issue would they choose -- and why?",
    context: "Centres the perspective of those who will live longest with current decisions.",
  },
  {
    id: "gov-10",
    category: "Governance",
    question: "What local regulation exists for good reason but hurts people it was never meant to affect?",
    context: "Surfaces unintended consequences of well-intentioned policy.",
  },
  {
    id: "gov-11",
    category: "Governance",
    question: "What public institution in your region is most responsive to ordinary people, and what makes it different?",
    context: "Identifies models of responsive governance worth replicating.",
  },
  {
    id: "gov-12",
    category: "Governance",
    question: "How transparent is the process by which major local projects are approved -- and what would real transparency look like?",
    context: "Examines the accessibility of civic decision-making.",
  },
  {
    id: "gov-13",
    category: "Governance",
    question: "What responsibility do citizens have when they disagree with a law -- and where is the line between dissent and disrespect?",
    context: "Navigates the tension between legal obligation and moral conscience.",
  },
  {
    id: "gov-14",
    category: "Governance",
    question: "If you could give one piece of unfiltered advice to the person who makes the biggest decisions in your region, what would it be?",
    context: "Channels ground-level insight directly to power.",
  },
  {
    id: "env-1",
    category: "Environment",
    question: "What environmental change have you witnessed in your lifetime that younger people in your region may not even know existed?",
    context: "Builds intergenerational environmental memory and urgency.",
  },
  {
    id: "env-2",
    category: "Environment",
    question: "What is the most practical environmental improvement your community could achieve in one year with existing resources?",
    context: "Focuses on actionable, near-term environmental wins.",
  },
  {
    id: "env-3",
    category: "Environment",
    question: "Who bears the greatest cost of local environmental degradation, and who profits from it?",
    context: "Surfaces environmental justice dimensions often overlooked.",
  },
  {
    id: "env-4",
    category: "Environment",
    question: "What natural feature of your region -- river, forest, wetland, coast -- is most at risk, and what would its loss mean?",
    context: "Anchors environmental concern in specific, loved places.",
  },
  {
    id: "env-5",
    category: "Environment",
    question: "What everyday habit in your community has the biggest hidden environmental cost that nobody talks about?",
    context: "Reveals normalised practices with outsized impact.",
  },
  {
    id: "env-6",
    category: "Environment",
    question: "How does your community`s relationship with water -- too much, too little, or too dirty -- shape daily life?",
    context: "Centres water as a universal and urgent environmental concern.",
  },
  {
    id: "env-7",
    category: "Environment",
    question: "What would it cost your community to become genuinely sustainable -- and who would pay?",
    context: "Confronts the economic reality of environmental transition.",
  },
  {
    id: "env-8",
    category: "Environment",
    question: "What species, plant, or ecosystem was common in your childhood but is now rare or gone?",
    context: "Uses personal memory to measure ecological decline.",
  },
  {
    id: "env-9",
    category: "Environment",
    question: "Where does your community`s waste actually go -- and who lives near that destination?",
    context: "Traces environmental burden to its physical and human endpoint.",
  },
  {
    id: "env-10",
    category: "Environment",
    question: "What local food could your region grow or produce for itself but currently imports instead?",
    context: "Identifies opportunities for localised food resilience.",
  },
  {
    id: "env-11",
    category: "Environment",
    question: "How has extreme weather in the last five years changed how people in your region think about the future?",
    context: "Connects climate experience to shifting psychology and planning.",
  },
  {
    id: "env-12",
    category: "Environment",
    question: "What industry or employer in your area would be most affected by serious environmental regulation -- and what would replace it?",
    context: "Surfaces the employment-environment tension honestly.",
  },
  {
    id: "env-13",
    category: "Environment",
    question: "What green space in your region is most threatened by development, and what is the argument for saving it?",
    context: "Activates local environmental protection instincts.",
  },
  {
    id: "env-14",
    category: "Environment",
    question: "If your grandchildren asked what you did about the environment, what would you want to say -- and what would the truth be?",
    context: "Creates intergenerational accountability through imagination.",
  },
  {
    id: "env-15",
    category: "Environment",
    question: "What renewable or sustainable practice already exists in your community that deserves to be celebrated and expanded?",
    context: "Builds on existing environmental strengths rather than only deficits.",
  },
  {
    id: "fam-1",
    category: "Family",
    question: "What pressure most threatens family wellbeing in your community -- financial, temporal, social, or something else?",
    context: "Identifies the primary stressor affecting family stability.",
  },
  {
    id: "fam-2",
    category: "Family",
    question: "What support do parents in your region actually need but cannot find?",
    context: "Maps the gap between family support services and real needs.",
  },
  {
    id: "fam-3",
    category: "Family",
    question: "How could your community better honour and include the wisdom of its elders?",
    context: "Explores intergenerational connection and elder inclusion.",
  },
  {
    id: "fam-4",
    category: "Family",
    question: "What does it mean to be a good neighbour to a family that is struggling -- without intruding or ignoring?",
    context: "Navigates the delicate balance between support and privacy.",
  },
  {
    id: "fam-5",
    category: "Family",
    question: "What family structure is most common in your community but least understood or supported by institutions?",
    context: "Surfaces the gap between social reality and institutional design.",
  },
  {
    id: "fam-6",
    category: "Family",
    question: "What skill or knowledge did your grandparents have that is rarely passed down today?",
    context: "Values intergenerational knowledge transfer and its erosion.",
  },
  {
    id: "fam-7",
    category: "Family",
    question: "How do working parents in your area manage the hours between school and work -- and what breaks in that system?",
    context: "Surfaces the invisible infrastructure of daily family survival.",
  },
  {
    id: "fam-8",
    category: "Family",
    question: "What would a truly child-friendly community look like -- not in theory, but in the details of a single day?",
    context: "Grounds child welfare in concrete daily experience.",
  },
  {
    id: "fam-9",
    category: "Family",
    question: "Who raises the children in your community when parents cannot -- and are they supported enough?",
    context: "Recognises kinship and informal care networks.",
  },
  {
    id: "fam-10",
    category: "Family",
    question: "What family tradition or ritual in your region is worth preserving, and what is quietly fading away?",
    context: "Maps cultural continuity and disruption at the household level.",
  },
  {
    id: "fam-11",
    category: "Family",
    question: "What is the hardest conversation families in your community are avoiding -- and what would make it safe to have?",
    context: "Surfaces taboo topics that fester in silence.",
  },
  {
    id: "fam-12",
    category: "Family",
    question: "How does your community treat the grieving -- and what would genuine care for the bereaved look like?",
    context: "Examines support systems during life`s most difficult transitions.",
  },
  {
    id: "fam-13",
    category: "Family",
    question: "What does financial security mean for a family in your region -- and how many actually have it?",
    context: "Grounds economic discussion in household reality.",
  },
  {
    id: "fam-14",
    category: "Family",
    question: "If a young person in your community asked you what makes a life worth living, what would you say -- and what would you hope they hear?",
    context: "Passes wisdom across generations with humility.",
  },
  {
    id: "econ-1",
    category: "Economy",
    question: "What skill or craft exists in your community that could become a sustainable livelihood if given the right support?",
    context: "Uncovers hidden economic potential at the grassroots.",
  },
  {
    id: "econ-2",
    category: "Economy",
    question: "Where does money leak out of your local economy, and what would keep it circulating locally?",
    context: "Reveals structural economic vulnerabilities and localisation opportunities.",
  },
  {
    id: "econ-3",
    category: "Economy",
    question: "What does \\\"a fair wage\\\" mean for the most common job in your region, and how far is reality from that standard?",
    context: "Grounds economic fairness debates in local lived experience.",
  },
  {
    id: "econ-4",
    category: "Economy",
    question: "What business in your community provides the most value per dollar -- and why is it not the biggest or most famous?",
    context: "Surfaces undervalued economic contributors.",
  },
  {
    id: "econ-5",
    category: "Economy",
    question: "How has the cost of housing changed the kind of people who can afford to live in your region?",
    context: "Traces economic exclusion through the housing market.",
  },
  {
    id: "econ-6",
    category: "Economy",
    question: "What essential good or service has become noticeably more expensive in your region -- and who is priced out?",
    context: "Maps inflation`s real human impact.",
  },
  {
    id: "econ-7",
    category: "Economy",
    question: "What would it take for a young person to start a business in your community -- and what stands in their way?",
    context: "Surfaces barriers to entrepreneurship and economic mobility.",
  },
  {
    id: "econ-8",
    category: "Economy",
    question: "Who in your community is one financial emergency away from crisis -- and what would genuine security look like for them?",
    context: "Reveals the precarity beneath apparent stability.",
  },
  {
    id: "econ-9",
    category: "Economy",
    question: "What local industry or employer is most at risk of disappearing -- and what would replace the jobs it provides?",
    context: "Anticipates economic transition and preparation needs.",
  },
  {
    id: "econ-10",
    category: "Economy",
    question: "How do people in your region define success -- and does that definition help or harm the community?",
    context: "Examines the relationship between personal ambition and collective wellbeing.",
  },
  {
    id: "econ-11",
    category: "Economy",
    question: "What form of exchange or trade happens informally in your community that no economist ever measures?",
    context: "Values non-monetary economic activity.",
  },
  {
    id: "econ-12",
    category: "Economy",
    question: "What public good would most improve economic opportunity in your region -- transport, childcare, internet, or something else?",
    context: "Identifies infrastructure gaps that constrain economic potential.",
  },
  {
    id: "econ-13",
    category: "Economy",
    question: "What does dignity in work look like for the lowest-paid workers in your community?",
    context: "Centres economic justice on those with the least power.",
  },
  {
    id: "econ-14",
    category: "Economy",
    question: "If your community had to become self-sufficient in one essential need, which would be the hardest -- and why?",
    context: "Tests economic resilience through scenario planning.",
  },
  {
    id: "econ-15",
    category: "Economy",
    question: "What economic inequality in your region is most carefully hidden from view?",
    context: "Surfaces the concealed dimensions of local wealth and poverty.",
  },
  {
    id: "edu-1",
    category: "Education",
    question: "What essential life skill is missing from the education young people receive in your area?",
    context: "Identifies curriculum gaps from a community perspective.",
  },
  {
    id: "edu-2",
    category: "Education",
    question: "Who in your community is the best teacher of things that matter, and why are they not formally recognised?",
    context: "Surfaces informal educators and knowledge keepers.",
  },
  {
    id: "edu-3",
    category: "Education",
    question: "What would education look like if it were designed by the students who struggle most with the current system?",
    context: "Centres the voices of those least served by existing structures.",
  },
  {
    id: "edu-4",
    category: "Education",
    question: "What do children in your region learn outside school that is more valuable than what they learn inside?",
    context: "Values experiential and community-based learning.",
  },
  {
    id: "edu-5",
    category: "Education",
    question: "How does access to good education in your area depend on where a family lives or how much they earn?",
    context: "Maps educational inequality to geography and wealth.",
  },
  {
    id: "edu-6",
    category: "Education",
    question: "What subject or topic is taught badly in your region not because teachers lack skill, but because the system prevents them from teaching well?",
    context: "Distinguishes between individual and systemic educational failure.",
  },
  {
    id: "edu-7",
    category: "Education",
    question: "What knowledge from your region`s history is most at risk of being forgotten -- and who is keeping it alive?",
    context: "Values local historical memory and its transmitters.",
  },
  {
    id: "edu-8",
    category: "Education",
    question: "How do young people in your community learn to be good citizens -- and is that learning enough?",
    context: "Examines civic education beyond the classroom.",
  },
  {
    id: "edu-9",
    category: "Education",
    question: "What would a school day look like if it were designed around how children actually learn best?",
    context: "Imagines child-centred educational design.",
  },
  {
    id: "edu-10",
    category: "Education",
    question: "Who in your community cannot access further education -- and what is the single biggest barrier?",
    context: "Surfaces exclusion from lifelong learning opportunities.",
  },
  {
    id: "edu-11",
    category: "Education",
    question: "What mistake from your own education do you most want to protect the next generation from repeating?",
    context: "Passes hard-won insight across generations.",
  },
  {
    id: "edu-12",
    category: "Education",
    question: "How does your community treat those who learn differently -- and what would genuine inclusion require?",
    context: "Examines educational equity for neurodiverse and differently-abled learners.",
  },
  {
    id: "edu-13",
    category: "Education",
    question: "What would it cost to give every child in your region an excellent education -- and what is currently spent instead?",
    context: "Confronts the resource gap in educational ambition versus reality.",
  },
  {
    id: "edu-14",
    category: "Education",
    question: "What is the most important thing a person can learn that no school currently teaches?",
    context: "Identifies the frontier of educational need.",
  },
  {
    id: "health-1",
    category: "Health",
    question: "What health concern is most discussed in private but rarely addressed publicly in your region?",
    context: "Surfaces stigmatised or hidden health issues.",
  },
  {
    id: "health-2",
    category: "Health",
    question: "What is the greatest barrier to wellbeing in your community -- access, cost, knowledge, trust, or something else?",
    context: "Pinpoints the primary obstacle to community health.",
  },
  {
    id: "health-3",
    category: "Health",
    question: "What traditional or local healing practice deserves more respect and integration into modern care?",
    context: "Values indigenous and community health knowledge.",
  },
  {
    id: "health-4",
    category: "Health",
    question: "How does loneliness or isolation affect physical health in your community -- and who is most at risk?",
    context: "Connects social and physical health.",
  },
  {
    id: "health-5",
    category: "Health",
    question: "What health service in your region works well but is underused because people do not know about it?",
    context: "Surfaces the awareness gap in health provision.",
  },
  {
    id: "health-6",
    category: "Health",
    question: "What daily habit in your community most damages long-term health -- and why is it so hard to change?",
    context: "Identifies entrenched behavioural health risks.",
  },
  {
    id: "health-7",
    category: "Health",
    question: "Who cares for the carers in your community -- and what happens when they burn out?",
    context: "Surfaces the invisible infrastructure of health support.",
  },
  {
    id: "health-8",
    category: "Health",
    question: "What would a genuinely preventative approach to health look like in your region?",
    context: "Shifts focus from treatment to prevention.",
  },
  {
    id: "health-9",
    category: "Health",
    question: "How does the physical environment of your community -- noise, air, space -- affect mental health?",
    context: "Connects urban and environmental design to psychological wellbeing.",
  },
  {
    id: "health-10",
    category: "Health",
    question: "What health emergency is your community least prepared for -- and what would readiness look like?",
    context: "Tests health resilience through scenario planning.",
  },
  {
    id: "health-11",
    category: "Health",
    question: "What do people in your region do for their health when formal care is too expensive, too far, or too slow?",
    context: "Surfaces informal health practices born of necessity.",
  },
  {
    id: "health-12",
    category: "Health",
    question: "How has the definition of a \\\"healthy life\\\" changed for people in your community over the last generation?",
    context: "Tracks shifting health values and expectations.",
  },
  {
    id: "health-13",
    category: "Health",
    question: "What would it take for every person in your community to sleep well, eat well, and move well?",
    context: "Imagines baseline health as a community infrastructure problem.",
  },
  {
    id: "health-14",
    category: "Health",
    question: "What health truth do you know from your own body that contradicts what experts say?",
    context: "Values embodied knowledge alongside professional expertise.",
  },
  {
    id: "just-1",
    category: "Justice",
    question: "Where do you see the gap between the law as written and justice as experienced in your community?",
    context: "Explores the lived distance between legal formalism and fairness.",
  },
  {
    id: "just-2",
    category: "Justice",
    question: "Who in your region is most likely to be treated unfairly by systems meant to protect them, and why?",
    context: "Identifies systemic bias and vulnerable populations.",
  },
  {
    id: "just-3",
    category: "Justice",
    question: "What would genuine accountability look like for the most powerful institution in your area?",
    context: "Challenges power asymmetries in accountability structures.",
  },
  {
    id: "just-4",
    category: "Justice",
    question: "When someone is wronged in your community, where do they turn first -- and does that place deliver justice?",
    context: "Maps the actual pathways to redress.",
  },
  {
    id: "just-5",
    category: "Justice",
    question: "What punishment or consequence in your region feels like revenge rather than repair?",
    context: "Distinguishes retributive from restorative approaches.",
  },
  {
    id: "just-6",
    category: "Justice",
    question: "Who in your community is trusted to resolve disputes, and what gives them that authority?",
    context: "Surfaces informal justice systems and their legitimacy.",
  },
  {
    id: "just-7",
    category: "Justice",
    question: "What does forgiveness mean in your community -- and when is it healing, and when is it premature?",
    context: "Navigates the moral complexity of forgiveness.",
  },
  {
    id: "just-8",
    category: "Justice",
    question: "How does your community treat those who have made serious mistakes -- and does that treatment help or harm?",
    context: "Examines rehabilitation and reintegration.",
  },
  {
    id: "just-9",
    category: "Justice",
    question: "What truth about your region`s past is most painful to acknowledge -- and what would acknowledging it change?",
    context: "Surfaces historical injustice and its ongoing effects.",
  },
  {
    id: "just-10",
    category: "Justice",
    question: "What rights do people in your community assume they have -- but cannot actually exercise?",
    context: "Maps the gap between nominal and effective rights.",
  },
  {
    id: "just-11",
    category: "Justice",
    question: "What would a truly fair process look like for deciding who gets scarce resources in your region?",
    context: "Imagines procedural justice in conditions of scarcity.",
  },
  {
    id: "just-12",
    category: "Justice",
    question: "How do you know when a community problem is best solved by rules, and when it is best solved by relationships?",
    context: "Navigates the tension between formal and informal justice.",
  },
  {
    id: "just-13",
    category: "Justice",
    question: "What injustice in your region has become so normal that most people no longer notice it?",
    context: "Surfaces normalised injustice.",
  },
  {
    id: "just-14",
    category: "Justice",
    question: "If you were wrongly accused of something serious in your community, would you trust the process to clear your name?",
    context: "Tests procedural trust through personal imagination.",
  },
  {
    id: "tech-1",
    category: "Technology",
    question: "What technology has improved life in your community, and what has quietly made it worse?",
    context: "Balances technological optimism with critical assessment.",
  },
  {
    id: "tech-2",
    category: "Technology",
    question: "Who in your region is being left behind by digital transformation, and what would inclusion actually require?",
    context: "Surfaces digital divides beyond simple access metrics.",
  },
  {
    id: "tech-3",
    category: "Technology",
    question: "If your community could design one piece of technology for itself, what problem would it solve?",
    context: "Centres community agency in technological development.",
  },
  {
    id: "tech-4",
    category: "Technology",
    question: "What personal information are people in your community giving away without realising its value?",
    context: "Surfaces data literacy gaps and their consequences.",
  },
  {
    id: "tech-5",
    category: "Technology",
    question: "How has the smartphone changed the way people in your region relate to one another -- for better and worse?",
    context: "Examines ubiquitous technology`s social effects.",
  },
  {
    id: "tech-6",
    category: "Technology",
    question: "What work in your community is most at risk of being replaced by automation -- and what would those workers do instead?",
    context: "Anticipates technological displacement and transition needs.",
  },
  {
    id: "tech-7",
    category: "Technology",
    question: "What would you want every child in your region to understand about how the internet actually works?",
    context: "Identifies critical digital literacy gaps.",
  },
  {
    id: "tech-8",
    category: "Technology",
    question: "How do algorithms shape what people in your community see, believe, and buy -- without their knowledge?",
    context: "Surfaces invisible algorithmic influence.",
  },
  {
    id: "tech-9",
    category: "Technology",
    question: "What low-tech solution in your community outperforms its high-tech equivalent?",
    context: "Values appropriate technology over technological escalation.",
  },
  {
    id: "tech-10",
    category: "Technology",
    question: "How would your community function if the internet went down for a week?",
    context: "Tests digital dependency and offline resilience.",
  },
  {
    id: "tech-11",
    category: "Technology",
    question: "What technological surveillance exists in your region that people accept without questioning?",
    context: "Surfaces normalised surveillance and its implications.",
  },
  {
    id: "tech-12",
    category: "Technology",
    question: "Who in your community benefits most from artificial intelligence, and who is most at risk from it?",
    context: "Anticipates AI`s uneven impact.",
  },
  {
    id: "tech-13",
    category: "Technology",
    question: "What technology from the past worked better than what replaced it -- and what did we lose?",
    context: "Values discontinued or superseded technologies.",
  },
  {
    id: "tech-14",
    category: "Technology",
    question: "If you could make one digital tool universally accessible in your community, what would it be and why?",
    context: "Prioritises digital inclusion through specific need.",
  },
  {
    id: "cult-1",
    category: "Culture",
    question: "What cultural practice or tradition in your region is dying that should be preserved -- and why is it fading?",
    context: "Identifies cultural erosion and its systemic causes.",
  },
  {
    id: "cult-2",
    category: "Culture",
    question: "Whose story is missing from how your community understands its own history?",
    context: "Surfaces historical silencing and narrative gaps.",
  },
  {
    id: "cult-3",
    category: "Culture",
    question: "What shared value still binds your community together, and what is most threatening to tear it apart?",
    context: "Maps social cohesion and its fractures.",
  },
  {
    id: "cult-4",
    category: "Culture",
    question: "What art, music, or craft is unique to your region -- and who is carrying it forward?",
    context: "Values local cultural expression and its transmitters.",
  },
  {
    id: "cult-5",
    category: "Culture",
    question: "How does your community welcome strangers -- and how does it protect itself from them?",
    context: "Examines the tension between openness and self-protection.",
  },
  {
    id: "cult-6",
    category: "Culture",
    question: "What language, dialect, or way of speaking in your region is disappearing -- and what is lost when it goes?",
    context: "Surfaces linguistic diversity and its erosion.",
  },
  {
    id: "cult-7",
    category: "Culture",
    question: "What does it mean to belong in your community -- and who decides who belongs?",
    context: "Examines inclusion, exclusion, and the boundaries of identity.",
  },
  {
    id: "cult-8",
    category: "Culture",
    question: "What celebration or ritual in your region brings the most diverse group of people together?",
    context: "Identifies cultural practices that bridge difference.",
  },
  {
    id: "cult-9",
    category: "Culture",
    question: "How does your community pass wisdom between generations -- and where does that chain break?",
    context: "Examines intergenerational cultural transmission.",
  },
  {
    id: "cult-10",
    category: "Culture",
    question: "What stereotype about your region is most unfair -- and what grain of truth does it contain?",
    context: "Navigates the complexity of regional identity.",
  },
  {
    id: "cult-11",
    category: "Culture",
    question: "What food in your region tells the most honest story about who lives there?",
    context: "Uses food as a lens for demographic and cultural history.",
  },
  {
    id: "cult-12",
    category: "Culture",
    question: "How has migration changed the cultural texture of your community -- and what tensions remain unresolved?",
    context: "Honours cultural change while acknowledging its difficulties.",
  },
  {
    id: "cult-13",
    category: "Culture",
    question: "What unwritten rule of behaviour in your community would confuse an outsider most?",
    context: "Surfaces implicit cultural norms.",
  },
  {
    id: "cult-14",
    category: "Culture",
    question: "What would your community look like if it deliberately preserved everything worth keeping and eagerly welcomed everything worth changing?",
    context: "Imagines a community that balances tradition and innovation.",
  },
  {
    id: "cult-15",
    category: "Culture",
    question: "What single story about your community is told too often -- and what more complicated truth does it hide?",
    context: "Challenges monolithic narratives with complexity.",
  },
]

export function getQuestionsByCategory(category: string): RevolutionaryQuestion[] {
  return revolutionaryQuestions.filter((q) => q.category === category)
}

export function getRandomQuestions(count: number = 8): RevolutionaryQuestion[] {
  const shuffled = [...revolutionaryQuestions].sort(() => Math.random() - 0.5)
  return shuffled.slice(0, count)
}

export function getQuestionsByCategories(categories: string[], perCategory: number = 2): RevolutionaryQuestion[] {
  const result: RevolutionaryQuestion[] = []
  for (const cat of categories) {
    const qs = getQuestionsByCategory(cat).sort(() => Math.random() - 0.5).slice(0, perCategory)
    result.push(...qs)
  }
  return result
}
